### ISSUE TITLE
128 bit integers in Rust 1.26

### ISSUE THREAD

**Issue by tueda** [fulmicoton/fastdivide#1]
Can `#![feature(i128_type)]` be removed as Rust [1.26](https://blog.rust-lang.org/2018/05/10/Rust-1.26.html) has been released?

**Comment by fulmicoton** [comment]
Sure.

**Comment by fulmicoton** [comment]
Fixed and published at `0.2`. This compiles in stable rust.

**Comment by tueda** [comment]
Thank you!
