### ISSUE TITLE
Support for #![no_std]

### ISSUE THREAD

**Issue by SharpCoder** [fulmicoton/fastdivide#3]
Hello!

This package would be great for `#![no_std]` applications. As it is right now, it does not seem to take any dependency on the standard lib. 

I wouldn't mind adding a feature flag to augment the `lib.rs` file so it includes `#![no_std]` when applicable, if that's something you would be interested in.

Cheers!

**Comment by fulmicoton** [comment]
Yes that would be great!

**Comment by SharpCoder** [comment]
Pull request #4  is merged. Closing issue. Thanks!
